import pb from '@/lib/pocketbase/client'
import type { DiscoveredProductRecord, ProductSnapshotRecord, WatchlistItemRecord, HunterSearchFilters, HunterSearchResult, HunterWhyAiPickedResult, InterpretedFiltersResult, ProductRecord } from '@/types/product'
const BASE_URL=import.meta.env.VITE_BACKEND_URL||`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/radar-api`
async function importOfficialProduct(url:string,product:DiscoveredProductRecord,fallback:string){const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${pb.authStore.token}`},body:JSON.stringify(product)});const data=await res.json().catch(()=>({}));if(!res.ok||!data?.success)throw new Error(data?.error||fallback);return data as {success:boolean;message:string;product:ProductRecord}}
export const hunterService={
 async searchMarketplace(filters:HunterSearchFilters):Promise<HunterSearchResult>{const isML=!filters.marketplace||filters.marketplace==='Mercado Livre',isShopee=filters.marketplace==='Shopee',isTikTok=filters.marketplace==='TikTok Shop';const url=isML?'/api/mercadolivre/search':isShopee?'/api/shopee/search':isTikTok?'/api/tiktok/search':`${BASE_URL}/backend/v1/hunter/search`;const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${pb.authStore.token}`},body:JSON.stringify(filters)});const raw=await res.text();let data:any={};try{data=raw?JSON.parse(raw):{}}catch{data={message:raw||`Resposta inválida do servidor (HTTP ${res.status}).`}}if(!res.ok)throw new Error(data.message||data.error||`Erro ao buscar produtos (${res.status})`);return data as HunterSearchResult},
 async runMercadoLivreProactiveNow(){const res=await fetch('/api/mercadolivre/proactive-now',{method:'POST',headers:{Authorization:`Bearer ${pb.authStore.token}`}});const data=await res.json().catch(()=>({}));if(!res.ok||!data?.success)throw new Error(data?.error||'Erro ao executar busca manual do Mercado Livre.');return data as {success:boolean;trend_keywords:number;candidates:number;saved:number;source:string}},
 async getProactiveOpportunities(limit=12){const res=await fetch(`/api/hunter/proactive?limit=${Math.max(1,Math.min(50,limit))}`,{headers:{Authorization:`Bearer ${pb.authStore.token}`}});const data=await res.json().catch(()=>({}));if(!res.ok||!data?.success)throw new Error(data?.error||'Erro ao carregar oportunidades proativas.');return Array.isArray(data.items)?data.items:[]},
 async updateProactiveStatus(id:string,status:'new'|'seen'|'ignored'|'imported'){const res=await fetch('/api/hunter/proactive',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${pb.authStore.token}`},body:JSON.stringify({id,status})});const data=await res.json().catch(()=>({}));if(!res.ok||!data?.success)throw new Error(data?.error||'Erro ao atualizar oportunidade.');return data.item},
 async getIntelligence(){const res=await fetch('/api/hunter/intelligence',{headers:{Authorization:`Bearer ${pb.authStore.token}`}});const data=await res.json().catch(()=>({}));if(!res.ok||!data?.success)throw new Error(data?.error||'Erro ao carregar inteligência do Hunter.');return data},
 async prepareAutonomousDecision(decisionId:string){const res=await fetch('/api/hunter/prepare',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${pb.authStore.token}`},body:JSON.stringify({decision_id:decisionId})});const data=await res.json().catch(()=>({}));if(!res.ok||!data?.success)throw new Error(data?.error||'Erro ao preparar campanha autônoma.');return data},
 async importMercadoLivreProduct(product:DiscoveredProductRecord){return importOfficialProduct('/api/mercadolivre/import',product,'Não foi possível adicionar o produto ao Radar.')},async importShopeeProduct(product:DiscoveredProductRecord){return importOfficialProduct('/api/shopee/import',product,'Não foi possível adicionar o produto Shopee ao Radar.')},async importTikTokShopProduct(product:DiscoveredProductRecord){return importOfficialProduct('/api/tiktok/import',product,'Não foi possível adicionar o produto TikTok Shop ao Radar.')},
 async findForMe(prompt:string):Promise<InterpretedFiltersResult>{const text=prompt.trim(),lower=text.toLowerCase(),toNumber=(raw?:string)=>raw?Number(raw.replace(/\./g,'').replace(',','.')):undefined;const max=lower.match(/(?:até|ate|max(?:imo)?|menos de)\s*r?\$?\s*(\d+[\d.,]*)/),min=lower.match(/(?:acima de|mais de|mínimo|minimo|a partir de)\s*r?\$?\s*(\d+[\d.,]*)/),sales=lower.match(/(?:pelo menos|mínimo|minimo|mais de)\s*(\d+)\s*(?:vendas?|vendidos?)/),rating=lower.match(/(?:nota|avaliação|avaliacao)\s*(?:mínima|minima|acima de|de)?\s*(\d(?:[.,]\d)?)/);const fallback=()=>({query:text,category:'',min_price:toNumber(min?.[1]),max_price:toNumber(max?.[1]),min_sales:sales?Number(sales[1]):undefined,min_rating:rating?Number(rating[1].replace(',','.')):undefined,estimated_commission_rate:undefined,ai_intent_summary:'Busca interpretada localmente e enviada para a API oficial do marketplace.'});try{const res=await fetch(`${BASE_URL}/backend/v1/hunter/find-for-me`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${pb.authStore.token}`},body:JSON.stringify({prompt})});if(!res.ok)return fallback();const data=await res.json();return data.interpreted_filters||fallback()}catch{return fallback()}},
 async whyAiPicked(productId:string,isDiscovered=true):Promise<HunterWhyAiPickedResult>{const res=await fetch(`${BASE_URL}/backend/v1/hunter/why-ai-picked`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${pb.authStore.token}`},body:JSON.stringify({id:productId,is_discovered:isDiscovered})});if(!res.ok){const err=await res.json().catch(()=>({}));throw new Error(err.error||'Erro ao carregar análise detalhada da IA')}return await res.json()},
 async approveProduct(discoveredId:string):Promise<{success:boolean;message:string;product:ProductRecord}>{const res=await fetch(`${BASE_URL}/backend/v1/hunter/approve`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${pb.authStore.token}`},body:JSON.stringify({id:discoveredId})});if(!res.ok){const err=await res.json().catch(()=>({}));throw new Error(err.error||'Erro ao aprovar produto para o Radar')}return await res.json()},async discardProduct(discoveredId:string){const res=await fetch(`${BASE_URL}/backend/v1/hunter/discard`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${pb.authStore.token}`},body:JSON.stringify({id:discoveredId})});if(!res.ok)throw new Error('Erro ao descartar produto');return await res.json()},async getDiscoveredProducts(status:'pending'|'approved'|'discarded'|'all'='pending',limit=50){const filter=status==='all'?'':`status = '${status}'`;const res=await pb.collection<DiscoveredProductRecord>('discovered_products').getList(1,limit,{filter,sort:'-opportunity_score,-created'});return res.items},async getTopOpportunitiesToday(limit=5){const res=await pb.collection<DiscoveredProductRecord>('discovered_products').getList(1,limit,{sort:'-opportunity_score'});return res.items}}
export const watchlistService={async getWatchlist():Promise<WatchlistItemRecord[]>{const res=await fetch(`${BASE_URL}/backend/v1/watchlist/items`,{headers:{Authorization:`Bearer ${pb.authStore.token}`}});if(!res.ok)throw new Error('Erro ao carregar Watchlist');const data=await res.json();return data.items||[]},async toggleWatchlist(item:any){const res=await fetch(`${BASE_URL}/backend/v1/watchlist/toggle`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${pb.authStore.token}`},body:JSON.stringify(item)});if(!res.ok)throw new Error('Erro ao atualizar Watchlist');return await res.json()},async getSnapshots(externalId:string){const res=await pb.collection<ProductSnapshotRecord>('product_snapshots').getList(1,20,{filter:`external_id = '${externalId}'`,sort:'-created'});return res.items}}