// Hook for Tracking Link Generator, Shopee SubID Builder & UTM Builder
// Routes:
//   POST /backend/v1/tracking/shopee/prepare-subids
//   POST /backend/v1/tracking/create-or-get

function cleanShopeeSubId(value, fallback) {
  const cleaned = String(value || '')
    .replace(/[^a-zA-Z0-9]/g, '')
    .slice(0, 48)
  return cleaned || fallback
}

function buildShopeeSubIds(body) {
  const campaignId = String(body.campaign_id || '')
  const creativeId = String(body.creative_id || '')
  const productId = String(body.product_id || '')
  const productTitle = String(body.product_title || '')
  const channel = String(body.channel || 'telegram')
  const variation = String(body.version_letter || body.variation || 'A').toUpperCase()

  const productSeed = productId
    ? 'prd' + productId.slice(-10)
    : cleanShopeeSubId(productTitle, 'produto').slice(0, 24)
  const channelSeed = cleanShopeeSubId(channel.toLowerCase(), 'canal')
  const campaignSeed = campaignId ? 'cmp' + campaignId.slice(-10) : 'campanha'
  const creativeSeed = creativeId ? 'cr' + creativeId.slice(-8) : 'criativo'
  const variationSeed = cleanShopeeSubId(variation, 'A')

  const generated = {
    sub_id_1: cleanShopeeSubId(productSeed, 'produto'),
    sub_id_2: cleanShopeeSubId(channelSeed, 'canal'),
    sub_id_3: cleanShopeeSubId(campaignSeed, 'campanha'),
    sub_id_4: cleanShopeeSubId(variationSeed + creativeSeed, 'Acriativo'),
    sub_id_5: cleanShopeeSubId(
      'rdr' +
        (campaignId ? campaignId.slice(-6) : 'cmp') +
        variationSeed +
        (creativeId ? creativeId.slice(-6) : 'crt') +
        channelSeed,
      'rdrtracking',
    ),
  }

  const supplied = body.shopee_sub_ids || {}
  return {
    sub_id_1: cleanShopeeSubId(supplied.sub_id_1, generated.sub_id_1),
    sub_id_2: cleanShopeeSubId(supplied.sub_id_2, generated.sub_id_2),
    sub_id_3: cleanShopeeSubId(supplied.sub_id_3, generated.sub_id_3),
    sub_id_4: cleanShopeeSubId(supplied.sub_id_4, generated.sub_id_4),
    sub_id_5: cleanShopeeSubId(supplied.sub_id_5, generated.sub_id_5),
  }
}

routerAdd(
  'POST',
  '/backend/v1/tracking/shopee/prepare-subids',
  (e) => {
    const userId = e.auth?.id
    if (!userId) return e.unauthorizedError('Autenticação necessária')

    const body = e.requestInfo().body || {}
    const subIds = buildShopeeSubIds(body)

    return e.json(200, {
      success: true,
      marketplace: 'Shopee',
      mode: 'advanced',
      allowed_characters: 'a-z A-Z 0-9',
      sub_ids: subIds,
      mapping: {
        sub_id_1: 'produto',
        sub_id_2: 'canal',
        sub_id_3: 'campanha',
        sub_id_4: 'variacao_criativo',
        sub_id_5: 'tracking_unico',
      },
      instructions:
        'Cole estes 5 valores nos campos Avançado da Shopee, gere o link afiliado na Shopee e depois salve esse link como destination_url no Radar.',
    })
  },
  $apis.requireAuth(),
)

routerAdd(
  'POST',
  '/backend/v1/tracking/create-or-get',
  (e) => {
    const userId = e.auth?.id
    if (!userId) return e.unauthorizedError('Autenticação necessária')

    const body = e.requestInfo().body || {}
    const campaignId = (body.campaign_id || '').trim()
    const variationId = (body.variation_id || '').trim()
    const creativeId = (body.creative_id || '').trim()
    const productId = (body.product_id || '').trim()
    const publicationId = (body.publication_id || '').trim()
    const channel = (body.channel || 'Instagram').trim()
    const originalDestination = (body.destination_url || '').trim()
    const isTestData = body.is_test_data === true
    const marketplace = (body.marketplace || '').trim()
    const isShopee = marketplace.toLowerCase() === 'shopee'

    if (!originalDestination) {
      return e.badRequestError('URL de destino é obrigatória')
    }

    try {
      const cShort = campaignId ? campaignId.slice(-6) : 'cmp'
      const vLetter = (body.version_letter || 'A').toUpperCase()
      const crShort = creativeId ? creativeId.slice(-6) : 'crt'
      const chClean = channel.toLowerCase().replace(/[^a-z0-9]/g, '')
      const genericSubId = `rdr_${cShort}_${vLetter}_${crShort}_${chClean}`
      const shopeeSubIds = isShopee ? buildShopeeSubIds(body) : null
      const subId = isShopee ? shopeeSubIds.sub_id_5 : genericSubId

      // IMPORTANT for Shopee:
      // the affiliate URL generated by Shopee already contains its attribution.
      // Do not append arbitrary parameters to s.shopee.com.br links.
      let finalDestUrl = originalDestination

      const utmSource = body.utm_source || chClean || 'radar_ia'
      const utmMedium = body.utm_medium || 'affiliate'
      const utmCampaign = body.utm_campaign || `camp_${cShort}`
      const utmContent = body.utm_content || `var_${vLetter}_${crShort}`
      const utmTerm = body.utm_term || ''

      if (!isShopee) {
        const separator = finalDestUrl.includes('?') ? '&' : '?'
        const utmParams = []
        if (!finalDestUrl.includes('utm_source='))
          utmParams.push(`utm_source=${encodeURIComponent(utmSource)}`)
        if (!finalDestUrl.includes('utm_medium='))
          utmParams.push(`utm_medium=${encodeURIComponent(utmMedium)}`)
        if (!finalDestUrl.includes('utm_campaign='))
          utmParams.push(`utm_campaign=${encodeURIComponent(utmCampaign)}`)
        if (!finalDestUrl.includes('utm_content='))
          utmParams.push(`utm_content=${encodeURIComponent(utmContent)}`)
        if (utmTerm && !finalDestUrl.includes('utm_term='))
          utmParams.push(`utm_term=${encodeURIComponent(utmTerm)}`)

        if (
          !finalDestUrl.includes('subid=') &&
          !finalDestUrl.includes('sub_id=') &&
          !finalDestUrl.includes('tag=')
        ) {
          utmParams.push(`subid=${encodeURIComponent(subId)}`)
        }

        if (utmParams.length > 0) {
          finalDestUrl = finalDestUrl + separator + utmParams.join('&')
        }
      }

      const trackCol = $app.findCollectionByNameOrId('tracking_links')
      let linkRec = null

      try {
        const matches = $app.findRecordsByFilter(
          'tracking_links',
          `user_id = '${userId}' && sub_id = '${subId}'`,
          '-created',
          1,
          0,
        )
        if (matches.length > 0) linkRec = matches[0]
      } catch (_) {}

      if (!linkRec) {
        const slug = $security.randomString(7).toLowerCase()
        linkRec = new Record(trackCol)
        linkRec.set('user_id', userId)
        linkRec.set('slug', slug)
        linkRec.set('title', body.title || `Link ${channel} - ${vLetter}`)
        linkRec.set('campaign_id', campaignId)
        linkRec.set('variation_id', variationId)
        linkRec.set('creative_id', creativeId)
        linkRec.set('product_id', productId)
        linkRec.set('publication_id', publicationId)
        linkRec.set('channel', channel)
        linkRec.set('sub_id', subId)
        linkRec.set('destination_url', finalDestUrl)
        linkRec.set('utm_source', utmSource)
        linkRec.set('utm_medium', utmMedium)
        linkRec.set('utm_campaign', utmCampaign)
        linkRec.set('utm_content', utmContent)
        linkRec.set('utm_term', utmTerm)
        linkRec.set('is_active', true)
        linkRec.set('is_test_data', isTestData)
        linkRec.set('raw_clicks_count', 0)
        linkRec.set('valid_clicks_count', 0)
        linkRec.set('conversions_count', 0)
        linkRec.set('commission_earned', 0)

        if (isShopee && shopeeSubIds) {
          linkRec.set('marketplace', 'Shopee')
          linkRec.set('sub_id_1', shopeeSubIds.sub_id_1)
          linkRec.set('sub_id_2', shopeeSubIds.sub_id_2)
          linkRec.set('sub_id_3', shopeeSubIds.sub_id_3)
          linkRec.set('sub_id_4', shopeeSubIds.sub_id_4)
          linkRec.set('sub_id_5', shopeeSubIds.sub_id_5)
        }

        linkRec.set('metadata', {
          original_affiliate_url: originalDestination,
          version_letter: vLetter,
          marketplace: isShopee ? 'Shopee' : marketplace || 'generic',
          shopee_sub_ids: shopeeSubIds || null,
          destination_preserved: isShopee,
        })
        $app.save(linkRec)
      } else {
        linkRec.set('destination_url', finalDestUrl)
        if (publicationId && !linkRec.getString('publication_id')) {
          linkRec.set('publication_id', publicationId)
        }
        if (body.is_test_data !== undefined) {
          linkRec.set('is_test_data', isTestData)
        }

        if (isShopee && shopeeSubIds) {
          linkRec.set('marketplace', 'Shopee')
          linkRec.set('sub_id_1', shopeeSubIds.sub_id_1)
          linkRec.set('sub_id_2', shopeeSubIds.sub_id_2)
          linkRec.set('sub_id_3', shopeeSubIds.sub_id_3)
          linkRec.set('sub_id_4', shopeeSubIds.sub_id_4)
          linkRec.set('sub_id_5', shopeeSubIds.sub_id_5)
        }
        $app.save(linkRec)
      }

      const slug = linkRec.getString('slug')
      const instanceUrl = $os.getenv('PB_INSTANCE_URL') || $os.getenv('SITE_URL') || ''
      const shortUrl = `${instanceUrl}/t/${slug}`

      return e.json(200, {
        success: true,
        tracking_link_id: linkRec.id,
        slug,
        short_url: shortUrl,
        sub_id: subId,
        marketplace: isShopee ? 'Shopee' : marketplace || '',
        shopee_sub_ids: shopeeSubIds,
        destination_url: finalDestUrl,
        destination_preserved: isShopee,
        raw_clicks: linkRec.getInt('raw_clicks_count') || 0,
        valid_clicks: linkRec.getInt('valid_clicks_count') || 0,
      })
    } catch (err) {
      console.log('Error creating tracking link:', err)
      return e.json(500, { error: 'Erro ao gerar link de tracking: ' + err.message })
    }
  },
  $apis.requireAuth(),
)
