migrate(
  (app) => {
    // 1. Brand Kits Collection (Minha Marca)
    const brandKits = new Collection({
      name: 'brand_kits',
      type: 'base',
      listRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
      createRule: "@request.auth.id != ''",
      updateRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id != ''",
      fields: [
        { name: 'user_id', type: 'relation', collectionId: '_pb_users_auth_', maxSelect: 1 },
        { name: 'brand_name', type: 'text', required: true },
        { name: 'logo_url', type: 'text' },
        { name: 'primary_color', type: 'text' }, // e.g. #00F2FF
        { name: 'secondary_color', type: 'text' }, // e.g. #7000FF
        { name: 'accent_color', type: 'text' }, // e.g. #FF3D00
        { name: 'background_color', type: 'text' }, // e.g. #0A0B10
        { name: 'text_color', type: 'text' }, // e.g. #FFFFFF
        { name: 'font_family', type: 'text' }, // 'Inter', 'Montserrat', 'Poppins', 'Roboto', 'Syne', etc.
        { name: 'visual_style', type: 'text' }, // 'modern_cyber', 'minimalist', 'high_converting_bold', 'clean_aesthetic', 'organic_creator'
        { name: 'tone_of_voice', type: 'text' }, // 'direto_persuasivo', 'consultivo', 'descontraido_humor', 'autoridade_tecnica', 'urgencia_oferta'
        { name: 'social_handle', type: 'text' }, // e.g. @achadosdoradar
        { name: 'signature_tagline', type: 'text' }, // e.g. "Achados testados e aprovados"
        { name: 'is_default', type: 'bool' },
        { name: 'metadata', type: 'json' },
        { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
        { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
      ],
      indexes: ['CREATE INDEX idx_brand_user ON brand_kits (user_id)'],
    })
    app.save(brandKits)

    // 2. Creative Projects Collection (Creatives / Estúdio Criativo)
    const creatives = new Collection({
      name: 'creatives',
      type: 'base',
      listRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
      createRule: "@request.auth.id != ''",
      updateRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id != ''",
      fields: [
        { name: 'user_id', type: 'relation', collectionId: '_pb_users_auth_', maxSelect: 1 },
        {
          name: 'campaign_id',
          type: 'relation',
          collectionId: app.findCollectionByNameOrId('campaigns').id,
          maxSelect: 1,
        },
        { name: 'campaign_variation_id', type: 'text' },
        { name: 'product_id', type: 'text' },
        { name: 'discovered_id', type: 'text' },
        { name: 'product_title', type: 'text', required: true },
        { name: 'product_image_url', type: 'text' }, // Original real product reference image
        { name: 'version_letter', type: 'text' }, // 'A' | 'B' | 'C'
        { name: 'hypothesis_type', type: 'text' }, // 'A_PROBLEMA' | 'B_DEMONSTRACAO' | 'C_BENEFICIO'
        { name: 'title', type: 'text', required: true },
        { name: 'creative_type', type: 'text', required: true }, // 'feed_1_1' | 'feed_4_5' | 'story_9_16' | 'reels_tiktok_9_16' | 'shorts_9_16' | 'pinterest' | 'banner' | 'carousel' | 'thumbnail' | 'short_video_storyboard'
        { name: 'width', type: 'number' },
        { name: 'height', type: 'number' },
        { name: 'aspect_ratio', type: 'text' }, // '1:1', '4:5', '9:16', '16:9', '2:3'
        {
          name: 'status',
          type: 'select',
          values: [
            'draft',
            'generating',
            'generated',
            'editing',
            'in_review',
            'approved',
            'ready_to_publish',
            'archived',
            'generation_failed',
          ],
          maxSelect: 1,
        },
        // Visual Concept created before image
        { name: 'visual_concept', type: 'json' }, // { concept_name, creative_angle, visual_hook_description, rationale, why_fits_audience, background_idea, lighting_mood }
        // Image generation data & fidelity tracking
        { name: 'image_provider', type: 'text' }, // 'openai' (real API) or 'none' / 'placeholder'
        { name: 'image_model', type: 'text' }, // e.g. 'dall-e-3' or 'gpt-image-1'
        { name: 'image_prompt', type: 'text' },
        { name: 'revised_prompt', type: 'text' },
        { name: 'image_url', type: 'text' }, // Active generated or uploaded visual image
        { name: 'is_ai_generated', type: 'bool' }, // true if generated by AI, false if original product image
        { name: 'fidelity_disclaimer_required', type: 'bool' }, // true => show "Representação conceitual gerada por IA."
        // Editable text and visual layout layers
        { name: 'text_layers', type: 'json' }, // { headline, subheadline, benefit, price_text, promo_price_text, cta_text, badge_tag, note_disclaimer, text_density_status: 'ideal'|'heavy' }
        { name: 'visual_style_overrides', type: 'json' }, // { primary_color, accent_color, font_family, text_align, background_overlay, logo_position }
        // Video Storyboard & Script details (Prepared for video, no fake rendering)
        { name: 'video_storyboard', type: 'json' }, // Array of scenes [{ scene_number, duration_sec, time_range, objective, camera_framing, required_visual, on_screen_text, narration_text, subtitle_text, transition_type, cta_action }]
        { name: 'video_provider', type: 'text' }, // 'none' (not configured)
        { name: 'narration_voice', type: 'text' }, // 'pt-BR-FranciscaNeural', 'pt-BR-AntonioNeural', etc.
        { name: 'narration_script', type: 'text' },
        { name: 'subtitles_text', type: 'text' },
        // Quality & Compliance review
        { name: 'creative_score', type: 'number' }, // 0 - 100 "Estimativa pré-teste da IA"
        { name: 'score_breakdown', type: 'json' }, // { visual_clarity, hook_power, product_highlight, readability, audience_fit, channel_fit, cta_power }
        {
          name: 'review_status',
          type: 'select',
          values: ['approved', 'needs_revision', 'blocked'],
          maxSelect: 1,
        },
        { name: 'review_report', type: 'json' }, // { distorted_product, invented_info, incorrect_price, unverified_discount, false_urgency, unreadable_text, excessive_text, inconsistent_cta, wrong_format, divergence_notes, flags: [] }
        // Commercial Revalidation check (before "Pronto para Publicar")
        { name: 'commercial_validation', type: 'json' }, // { product_still_available, current_price, current_promo_price, affiliate_link_valid, campaign_approved, creative_approved, last_validated_at }
        // Version control & Active version
        { name: 'current_version', type: 'number' }, // 1, 2, 3...
        { name: 'version_count', type: 'number' },
        // Future metrics tracking
        { name: 'impressions', type: 'number' },
        { name: 'views', type: 'number' },
        { name: 'retention_rate', type: 'number' },
        { name: 'clicks', type: 'number' },
        { name: 'ctr', type: 'number' },
        { name: 'conversions', type: 'number' },
        { name: 'sales_count', type: 'number' },
        { name: 'total_commission', type: 'number' },
        { name: 'roi', type: 'number' },
        { name: 'metadata', type: 'json' },
        { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
        { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
      ],
      indexes: [
        'CREATE INDEX idx_creative_user ON creatives (user_id)',
        'CREATE INDEX idx_creative_camp ON creatives (campaign_id)',
        'CREATE INDEX idx_creative_status ON creatives (status)',
        'CREATE INDEX idx_creative_score ON creatives (creative_score DESC)',
        'CREATE INDEX idx_creative_type ON creatives (creative_type)',
      ],
    })
    app.save(creatives)

    // 3. Creative Versions History Collection (V1, V2, V3...)
    const creativeVersions = new Collection({
      name: 'creative_versions',
      type: 'base',
      listRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
      createRule: "@request.auth.id != ''",
      updateRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id != ''",
      fields: [
        {
          name: 'creative_id',
          type: 'relation',
          collectionId: creatives.id,
          cascadeDelete: true,
          maxSelect: 1,
          required: true,
        },
        { name: 'version_number', type: 'number', required: true },
        { name: 'version_tag', type: 'text' }, // e.g. "V1 - Conceito Inicial", "V2 - Headline mais curta"
        { name: 'image_url', type: 'text' },
        { name: 'image_prompt', type: 'text' },
        { name: 'text_layers', type: 'json' },
        { name: 'video_storyboard', type: 'json' },
        { name: 'visual_concept', type: 'json' },
        { name: 'creative_score', type: 'number' },
        { name: 'review_status', type: 'text' },
        { name: 'change_summary', type: 'text' },
        { name: 'metadata', type: 'json' },
        { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
        { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
      ],
      indexes: [
        'CREATE INDEX idx_cvers_creative ON creative_versions (creative_id)',
        'CREATE INDEX idx_cvers_num ON creative_versions (creative_id, version_number)',
      ],
    })
    app.save(creativeVersions)

    // 4. Creative Assets Library Collection (original, generated, thumbnails, audio, logo)
    const creativeAssets = new Collection({
      name: 'creative_assets',
      type: 'base',
      listRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
      createRule: "@request.auth.id != ''",
      updateRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id != ''",
      fields: [
        { name: 'user_id', type: 'relation', collectionId: '_pb_users_auth_', maxSelect: 1 },
        { name: 'creative_id', type: 'text' },
        { name: 'campaign_id', type: 'text' },
        { name: 'product_id', type: 'text' },
        { name: 'asset_type', type: 'text', required: true }, // 'original_product_image' | 'ai_generated_image' | 'edited_canvas' | 'thumbnail' | 'logo' | 'storyboard_frame' | 'video_draft' | 'audio_narration'
        { name: 'format_name', type: 'text' }, // 'Feed 1:1', 'Feed 4:5', 'Story 9:16', 'Reel 9:16', 'Banner', etc.
        { name: 'version_letter', type: 'text' }, // 'A' | 'B' | 'C'
        { name: 'file_url', type: 'text', required: true },
        { name: 'file_name', type: 'text' },
        { name: 'mime_type', type: 'text' },
        { name: 'width', type: 'number' },
        { name: 'height', type: 'number' },
        { name: 'is_ai_generated', type: 'bool' },
        { name: 'notes', type: 'text' },
        { name: 'metadata', type: 'json' },
        { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
        { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
      ],
      indexes: [
        'CREATE INDEX idx_asset_user ON creative_assets (user_id)',
        'CREATE INDEX idx_asset_camp ON creative_assets (campaign_id)',
        'CREATE INDEX idx_asset_type ON creative_assets (asset_type)',
      ],
    })
    app.save(creativeAssets)
  },
  (app) => {
    try {
      const assets = app.findCollectionByNameOrId('creative_assets')
      app.delete(assets)
    } catch (_) {}
    try {
      const versions = app.findCollectionByNameOrId('creative_versions')
      app.delete(versions)
    } catch (_) {}
    try {
      const creatives = app.findCollectionByNameOrId('creatives')
      app.delete(creatives)
    } catch (_) {}
    try {
      const brandKits = app.findCollectionByNameOrId('brand_kits')
      app.delete(brandKits)
    } catch (_) {}
  },
)
