import { decryptMlSession, encryptMlSession, type MlSession } from '../../server/mercadolivre.js'

const SUPABASE_URL=process.env.SUPABASE_URL||'https://nqepcuktmbnjecjlemmh.supabase.co'
const BRIDGE=`${SUPABASE_URL}/functions/v1/mercadolivre-cron-bridge`
function clamp(n:number,min:number,max:number){return Math.max(min,Math.min(max,n))}
function scoreCandidate(trendPosition:number,highlightPosition:number,sold:number,price:number,freeShipping:boolean){let score=62;score+=Math.max(2,12-trendPosition);score+=Math.max(2,12-Math.floor(highlightPosition/2));if(sold>=1000)score+=8;else if(sold>=500)score+=6;else if(sold>=100)score+=4;else if(sold>=20)score+=2;if(price>=20&&price<=800)score+=3;if(freeShipping)score+=2;return clamp(Math.round(score),0,96)}
async function bridge(token:string,body:Record<string,unknown>){const r=await fetch(BRIDGE,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||`Mercado Livre bridge HTTP ${r.status}`);return d}
async function mlJson(url:string,token:string){const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`,Accept:'application/json','User-Agent':'RadarIA/1.0'}});const d=await r.json().catch(()=>({}));if(!r.ok){const e:any=new Error(d?.message||d?.error||`Mercado Livre HTTP ${r.status}`);e.status=r.status;throw e}return d}
function validItem(item:any){return Boolean(item?.id&&item?.permalink&&Number(item?.price||0)>0)}
async function getItem(id:string,token:string){const item=await mlJson(`https://api.mercadolibre.com/items/${encodeURIComponent(id)}`,token);return validItem(item)?item:null}
async function bestItem(ids:string[],token:string){let best:any=null;for(const id of ids.slice(0,6)){try{const item=await getItem(id,token);if(!item)continue;if(!best||Number(item?.sold_quantity||0)>Number(best?.sold_quantity||0))best=item}catch{}}return best}
async function resolveUserProduct(id:string,token:string){const up=await mlJson(`https://api.mercadolibre.com/user-products/${encodeURIComponent(id)}`,token);const sellerId=String(up?.user_id||'');if(!sellerId)return null;const u=new URL(`https://api.mercadolibre.com/users/${encodeURIComponent(sellerId)}/items/search`);u.searchParams.set('user_product_id',id);u.searchParams.set('limit','10');const found=await mlJson(u.toString(),token);const ids=(Array.isArray(found?.results)?found.results:[]).map((x:any)=>String(x||'')).filter(Boolean);return bestItem(ids,token)}
async function resolveProduct(id:string,token:string){const product=await mlJson(`https://api.mercadolibre.com/products/${encodeURIComponent(id)}`,token);const winnerId=String(product?.buy_box_winner?.item_id||'');if(winnerId){try{const winner=await getItem(winnerId,token);if(winner)return winner}catch{}}try{const offers=await mlJson(`https://api.mercadolibre.com/products/${encodeURIComponent(id)}/items?limit=20`,token);const ids=(Array.isArray(offers?.results)?offers.results:[]).map((x:any)=>String(x?.item_id||x?.id||'')).filter(Boolean);return await bestItem(ids,token)}catch{return null}}
async function resolveHighlight(entry:any,token:string){const id=String(entry?.id||''),type=String(entry?.type||'').toUpperCase();if(!id)return null;if(type==='USER_PRODUCT')return resolveUserProduct(id,token);if(type==='PRODUCT')return resolveProduct(id,token);if(type==='ITEM'){try{return await getItem(id,token)}catch{if(id.startsWith('MLBU'))return resolveUserProduct(id,token);return null}}if(id.startsWith('MLBU'))return resolveUserProduct(id,token);return null}
async function refreshSession(session:MlSession,secret:string,appId:string){if(session.expires_at&&Date.now()<Number(session.expires_at)-120000)return{session,refreshed:false};if(!session.refresh_token)throw new Error('Sessão Mercado Livre sem refresh token.');const form=new URLSearchParams();form.set('grant_type','refresh_token');form.set('client_id',appId);form.set('client_secret',secret);form.set('refresh_token',session.refresh_token);const r=await fetch('https://api.mercadolibre.com/oauth/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json'},body:form.toString()});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.access_token)throw new Error(d?.message||d?.error||'Falha ao renovar Mercado Livre.');return{refreshed:true,session:{access_token:d.access_token,refresh_token:d.refresh_token||session.refresh_token,expires_at:Date.now()+Number(d.expires_in||21600)*1000,user_id:d.user_id||session.user_id,scope:d.scope||session.scope,token_type:d.token_type||session.token_type}as MlSession}}

export default async function handler(req:any,res:any){
  res.setHeader('Cache-Control','no-store');if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'})
  const oidc=String(req.headers['x-vercel-oidc-token']||process.env.VERCEL_OIDC_TOKEN||''),secret=process.env.MERCADO_LIVRE_CLIENT_SECRET||'',appId=process.env.MERCADO_LIVRE_APP_ID||'',runId=crypto.randomUUID();let claimed=false
  try{
    if(!oidc)throw new Error('Vercel OIDC token ausente.');if(!secret||!appId)throw new Error('Credenciais do Mercado Livre não configuradas.')
    const claim=await bridge(oidc,{mode:'claim',run_id:runId});if(!claim?.allowed)return res.status(200).json({success:true,skipped:true,reason:'cooldown'});claimed=true
    const source=await bridge(oidc,{mode:'connections',run_id:runId}),connections=Array.isArray(source?.connections)?source.connections:[],all=new Map<string,any>()
    let trendKeywords=0,categoriesPredicted=0,highlightsChecked=0,itemsResolved=0,skippedUpstream=0
    for(const connection of connections){
      if(!connection?.credentials_encrypted||!connection?.user_id)continue
      let session=decryptMlSession(String(connection.credentials_encrypted),secret);const refreshed=await refreshSession(session,secret,appId);session=refreshed.session
      if(refreshed.refreshed)await bridge(oidc,{mode:'update_connection',run_id:runId,connection_id:connection.id,user_id:connection.user_id,credentials_encrypted:encryptMlSession(session,secret)})
      const trends=await mlJson('https://api.mercadolibre.com/trends/MLB',session.access_token),keywords=(Array.isArray(trends)?trends:[]).map((x:any)=>String(x?.keyword||'').trim()).filter(Boolean).slice(0,12);trendKeywords+=keywords.length
      for(let i=0;i<keywords.length;i++){
        const keyword=keywords[i]
        try{
          const p=new URL('https://api.mercadolibre.com/sites/MLB/domain_discovery/search');p.searchParams.set('q',keyword);p.searchParams.set('limit','3')
          const predicted=await mlJson(p.toString(),session.access_token),cats=(Array.isArray(predicted)?predicted:[]).map((x:any)=>({id:String(x?.category_id||''),domain:String(x?.domain_id||'')})).filter((x:any)=>x.id);categoriesPredicted+=cats.length
          let content:any[]=[],categoryId='',domainId=''
          for(const cat of cats){try{const h=await mlJson(`https://api.mercadolibre.com/highlights/MLB/category/${encodeURIComponent(cat.id)}`,session.access_token),c=Array.isArray(h?.content)?h.content:[];if(c.length){content=c;categoryId=cat.id;domainId=cat.domain;break}}catch{}}
          if(!content.length){skippedUpstream++;continue}highlightsChecked+=content.length
          for(const entry of content.slice(0,12)){try{const item=await resolveHighlight(entry,session.access_token);if(!validItem(item))continue;itemsResolved++;const sold=Number(item?.sold_quantity||0),price=Number(item?.price||0),freeShipping=Boolean(item?.shipping?.free_shipping),position=Number(entry?.position||20),score=scoreCandidate(i+1,position,sold,price,freeShipping),externalId=String(item.id);const row={user_id:connection.user_id,niche_key:String(domainId||item?.category_id||categoryId||'mercadolivre_highlights').toLowerCase(),search_query:keyword,external_id:externalId,title:String(item.title||keyword),image_url:String(item?.pictures?.[0]?.secure_url||item?.thumbnail||'').replace(/^http:/,'https:'),product_url:String(item.permalink),affiliate_url:null,price,commission_rate:0,commission_amount:0,sales_count:sold,rating:0,base_score:score,niche_confidence:0,proactive_score:score,reason:{source:'mercadolivre_trends_highlights_v2',trend_keyword:keyword,trend_position:i+1,highlight_position:position,highlight_type:String(entry?.type||''),category_id:categoryId,free_shipping:freeShipping,conversion_learning_enabled:false,affiliate_link_required_after_selection:true,autonomous_prepare_enabled:false}};const k=`${connection.user_id}:${externalId}`,prev=all.get(k);if(!prev||Number(prev.proactive_score||0)<score)all.set(k,row)}catch{skippedUpstream++}}
        }catch{skippedUpstream++}
      }
    }
    const candidates=[...all.values()].sort((a,b)=>Number(b.proactive_score)-Number(a.proactive_score)).slice(0,Math.max(10,connections.length*20)),saved=await bridge(oidc,{mode:'ingest',run_id:runId,candidates});claimed=false
    return res.status(200).json({success:true,connections:connections.length,trend_keywords:trendKeywords,categories_predicted:categoriesPredicted,highlights_checked:highlightsChecked,items_resolved:itemsResolved,candidates:candidates.length,saved:Number(saved?.saved||0),skipped_upstream:skippedUpstream,source:'mercadolivre_trends_highlights_v2'})
  }catch(err:any){const message=String(err?.message||err||'Falha desconhecida.');if(claimed){try{await bridge(oidc,{mode:'fail',run_id:runId,error:message,stage:'mercadolivre_highlights'})}catch{}}return res.status(500).json({success:false,error:message})}
}
