import React,{useEffect,useState}from'react'
import{Compass,Search,Sparkles,RefreshCw,ShieldCheck,Radar as RadarIcon,BrainCircuit,SlidersHorizontal,Layers}from'lucide-react'
import{Button}from'@/components/ui/button'
import{DiscoveredProductCard}from'@/components/DiscoveredProductCard'
import{hunterService,watchlistService}from'@/services/hunter'
import type{DiscoveredProductRecord,HunterSearchFilters}from'@/types/product'
import{toast}from'sonner'
const ORIGIN='https://radar-de-produtos-ia-l7t2mrlbl.vercel.app'
function ensure(){if(typeof window==='undefined')return true;if(window.location.hostname.endsWith('.vercel.app')&&window.location.origin!==ORIGIN){window.location.replace(ORIGIN+window.location.pathname+window.location.search+window.location.hash);return false}return true}
function pp(x:any):DiscoveredProductRecord{return{id:`proactive_${x.id}`,external_id:String(x.external_id||''),platform:String(x.platform||'Shopee'),title:String(x.title||''),image_url:x.image_url||'',category:String(x.niche_key||'Shopee'),niche:String(x.niche_key||''),price:Number(x.price||0),promo_price:Number(x.price||0),commission_rate:Number(x.commission_rate||0),commission_amount:Number(x.commission_amount||0),sales_count:Number(x.sales_count||0),reviews_count:0,rating:Number(x.rating||0),seller:'',product_url:x.product_url||'',affiliate_url:x.affiliate_url||'',competition_level:0,trends_score:0,demand_score:Number(x.sales_count||0),opportunity_score:Number(x.proactive_score||0),opportunity_level:Number(x.proactive_score||0)>=80?'hot':Number(x.proactive_score||0)>=65?'good':'test',status:'pending',source:'shopee_affiliate_api',raw_data:{proactive:true,proactive_id:x.id,niche_confidence:Number(x.niche_confidence||0),base_score:Number(x.base_score||0),reason:x.reason||{}},created:x.discovered_at||'',updated:x.last_seen_at||''}as any}
const perfLabel=(v:any)=>({collect_data:'COLETAR DADOS',keep_testing:'MANTER TESTE',pause_candidate:'PAUSAR CANDIDATO',scale_candidate:'ESCALAR CANDIDATO'}as any)[String(v)]||'COLETAR DADOS'
const perfTone=(v:any)=>String(v)==='scale_candidate'?'text-emerald-400':String(v)==='pause_candidate'?'text-rose-400':String(v)==='keep_testing'?'text-amber-300':'text-gray-400'
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1"><label className="text-[11px] font-semibold text-gray-300">{label}</label>{children}</div>}
function scanDate(v:any){try{return new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}catch{return String(v||'')}}
export default function HunterPage(){
 const[query,setQuery]=useState(''),[category,setCategory]=useState('Todas'),[minPrice,setMinPrice]=useState<number|''>(''),[maxPrice,setMaxPrice]=useState<number|''>(''),[minSales,setMinSales]=useState<number|''>(''),[minRating,setMinRating]=useState<number|''>(''),[estimatedCommissionRate,setEstimatedCommissionRate]=useState<number|''>(''),[marketplace,setMarketplace]=useState('Shopee'),[limit,setLimit]=useState(30),[nextOffset,setNextOffset]=useState(0),[hasMore,setHasMore]=useState(false),[results,setResults]=useState<DiscoveredProductRecord[]>([]),[proactive,setProactive]=useState<DiscoveredProductRecord[]>([]),[scanHistory,setScanHistory]=useState<any[]>([]),[intel,setIntel]=useState<any>(null),[searching,setSearching]=useState(false),[loadingMore,setLoadingMore]=useState(false),[watch,setWatch]=useState<Set<string>>(new Set()),[natural,setNatural]=useState(''),[parsing,setParsing]=useState(false),[preparing,setPreparing]=useState(''),[mlManualRunning,setMlManualRunning]=useState(false)
 const loadIntel=()=>hunterService.getIntelligence().then(setIntel).catch(()=>{})
 const loadProactive=()=>hunterService.getProactiveOpportunities(12).then(xs=>setProactive(xs.map(pp)))
 const loadScanHistory=()=>hunterService.getScanHistory(10,'Mercado Livre').then(setScanHistory).catch(()=>{})
 useEffect(()=>{if(!ensure())return;Promise.allSettled([watchlistService.getWatchlist().then(xs=>setWatch(new Set(xs.flatMap(x=>[x.external_id,x.title].filter(Boolean)as string[])))),loadProactive(),loadIntel(),loadScanHistory()])},[])
 const filters=(offset=0):HunterSearchFilters=>({query,category,marketplace,limit,offset,min_price:typeof minPrice==='number'?minPrice:undefined,max_price:typeof maxPrice==='number'?maxPrice:undefined,min_sales:typeof minSales==='number'?minSales:undefined,min_rating:typeof minRating==='number'?minRating:undefined,estimated_commission_rate:typeof estimatedCommissionRate==='number'?estimatedCommissionRate:undefined})
 const search=async(o?:Partial<HunterSearchFilters>)=>{const q=o?.query??query;if(!q?.trim()&&category==='Todas'&&!o?.category)return toast.error('Informe uma palavra-chave.');setSearching(true);try{const r=await hunterService.searchMarketplace({...filters(0),...o,query:q||'',offset:0});setResults(r.products||[]);setNextOffset(r.next_offset||r.products?.length||0);setHasMore(Boolean(r.has_more));toast.success(`${r.products?.length||0} produtos encontrados na ${o?.marketplace||marketplace}.`)}catch(e:any){toast.error(e.message||'Falha ao buscar produtos.')}finally{setSearching(false)}}
 const loadMore=async()=>{setLoadingMore(true);try{const r=await hunterService.searchMarketplace(filters(nextOffset));setResults(prev=>{const seen=new Set(prev.map(p=>p.external_id||p.id));return[...prev,...(r.products||[]).filter(p=>!seen.has(p.external_id||p.id))]});setNextOffset(r.next_offset||nextOffset+(r.products?.length||0));setHasMore(Boolean(r.has_more))}catch(e:any){toast.error(e.message||'Erro ao carregar mais produtos.')}finally{setLoadingMore(false)}}
 const find=async(e:any)=>{e.preventDefault();if(!natural.trim())return;setParsing(true);try{const p=await hunterService.findForMe(natural);setQuery(p.query||natural);if(p.category)setCategory(p.category);if(p.min_price!=null)setMinPrice(p.min_price);if(p.max_price!=null)setMaxPrice(p.max_price);if(p.min_sales!=null)setMinSales(p.min_sales);if(p.min_rating!=null)setMinRating(p.min_rating);if(p.estimated_commission_rate!=null)setEstimatedCommissionRate(p.estimated_commission_rate);await search({query:p.query||natural,category:p.category||category,min_price:p.min_price,max_price:p.max_price,min_sales:p.min_sales,min_rating:p.min_rating,estimated_commission_rate:p.estimated_commission_rate})}catch(e:any){toast.error(e.message||'Erro ao interpretar a busca.')}finally{setParsing(false)}}
 const approve=async(p:any)=>{try{if(p.source==='mercadolivre_api'||p.source==='mercadolivre_catalog_api'||p.platform==='Mercado Livre')await hunterService.importMercadoLivreProduct(p);else if(p.source==='shopee_affiliate_api')await hunterService.importShopeeProduct(p);else if(p.source==='tiktok_shop_creator_api'||p.platform==='TikTok Shop')await hunterService.importTikTokShopProduct(p);else await hunterService.approveProduct(p.id);setResults(x=>x.filter(y=>y.id!==p.id));setProactive(x=>x.filter(y=>y.id!==p.id));loadIntel();toast.success('Produto salvo no Radar.')}catch(e:any){toast.error(e.message||'Erro ao salvar produto.')}}
 const discard=async(p:any)=>{try{const pid=p.raw_data?.proactive_id;if(pid)await hunterService.updateProactiveStatus(pid,'ignored');setResults(x=>x.filter(y=>y.id!==p.id));setProactive(x=>x.filter(y=>y.id!==p.id));toast.success(pid?'Oportunidade ignorada e não voltará como nova.':'Produto removido da lista.')}catch(e:any){toast.error(e.message||'Erro ao ignorar oportunidade.')}}
 const why=async(p:any)=>{try{const r=await hunterService.whyAiPicked(p.id,true);toast.info(r?.explanation||r?.reason||'Análise detalhada carregada.')}catch{toast.info('Análise detalhada disponível após salvar o produto no Radar.')}}
 const toggle=async(p:any)=>{try{const k=p.external_id||p.title,r=await watchlistService.toggleWatchlist({external_id:k,platform:p.platform,title:p.title,image_url:p.image_url,product_url:p.product_url,category:p.category,price:p.promo_price||p.price,commission_rate:p.commission_rate,commission_amount:p.commission_amount,sales_count:p.sales_count,rating:p.rating,opportunity_score:p.opportunity_score});setWatch(s=>{const n=new Set(s);r.action==='added'?n.add(k):n.delete(k);return n})}catch{toast.error('Erro ao atualizar Watchlist.')}}
 const prepare=async(d:any)=>{setPreparing(d.id);try{const r=await hunterService.prepareAutonomousDecision(d.id);toast.success(`Campanha ${String(r.decision||'').toUpperCase()} preparada com rastreamento.`);await loadIntel();setProactive(xs=>xs.filter(p=>p.raw_data?.proactive_id!==d.opportunity_id))}catch(e:any){toast.error(e.message||'Erro ao preparar campanha.')}finally{setPreparing('')}}
 const runMlNow=async()=>{setMlManualRunning(true);try{const r=await hunterService.runMercadoLivreProactiveNow();await Promise.allSettled([loadProactive(),loadScanHistory()]);const failures=(r.diagnostics||[]).filter(d=>d.error),first=failures[0];const msg=`Mercado Livre: ${r.trend_keywords} tendências • ${r.categories_predicted||0} categorias previstas • ${r.highlights_checked||0} posições de mais vendidos • ${r.items_resolved||0} anúncios resolvidos • ${r.candidates} oportunidades • ${r.saved} salvas${failures.length?` • ${failures.length} falhas${first?` • ${first.keyword}: HTTP ${first.status||'?'} ${first.error}`:''}`:''}.`;r.candidates===0&&failures.length?toast.error(msg,{duration:12000}):toast.success(msg,{duration:10000})}catch(e:any){toast.error(e.message||'Falha na busca manual do Mercado Livre.',{duration:12000})}finally{setMlManualRunning(false)}}
 const t=intel?.totals||{clicks:0,conversions:0,commission:0,conversion_rate:0},decisions=intel?.autonomous_decisions||[]
 const marketLabel=marketplace==='Shopee'?'Shopee Affiliate Open API':marketplace==='TikTok Shop'?'TikTok Shop Creator Affiliate API':'Mercado Livre API oficial'
 return <div className="space-y-6 max-w-7xl mx-auto pb-16">
  <div className="pb-4 border-b border-[#1E2232]"><div className="text-[10px] text-[#00F2FF] flex gap-2"><ShieldCheck className="w-3 h-3"/>APIS OFICIAIS CONECTADAS</div><h1 className="text-3xl font-extrabold text-white flex gap-2"><Compass className="w-7"/>Caçador de Oportunidades</h1><p className="text-sm text-gray-400 mt-1">Busque produtos reais e deixe o Hunter aprender com cliques e vendas.</p></div>
  <div className="p-5 rounded-2xl bg-[#121522] border border-[#7000FF]/35"><h2 className="text-sm font-bold text-white flex gap-2 mb-4"><BrainCircuit className="w-4 text-[#00F2FF]"/>Inteligência do Hunter</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Cliques válidos',t.clicks],['Conversões',t.conversions],['Taxa de conversão',`${t.conversion_rate}%`],['Comissão',`R$ ${Number(t.commission).toFixed(2)}`]].map(([a,b])=><div className="p-3 bg-[#0B0D14] rounded-xl border border-[#232738]" key={String(a)}><div className="text-[10px] text-gray-400">{a}</div><div className="text-xl font-extrabold text-white">{b}</div></div>)}</div><div className="mt-4 text-xs text-gray-400">{intel?.niches?.length?`Nichos aprendidos: ${intel.niches.slice(0,4).map((n:any)=>`${n.niche_key} (${Number(n.confidence_score).toFixed(0)})`).join(' • ')}`:'Ainda sem conversões suficientes para formar um nicho vencedor.'}</div></div>
  <div className="p-5 rounded-2xl bg-[#15131f] border border-[#9333EA]/35"><div className="flex items-center justify-between mb-3"><div><h2 className="text-sm font-bold text-white flex gap-2"><BrainCircuit className="w-4 text-[#A855F7]"/>Decisões Autônomas</h2><p className="text-xs text-gray-400 mt-1">O Hunter decide promover, testar ou observar e acompanha o desempenho real. Nenhuma publicação ou gasto é feito sozinho.</p></div><span className="text-[10px] text-[#A855F7] font-mono">{decisions.length} PENDENTES</span></div>{decisions.length?<div className="space-y-2">{decisions.slice(0,8).map((d:any)=><div key={d.id} className="flex flex-col md:flex-row md:items-center justify-between gap-3 p-3 rounded-xl bg-[#0B0D14] border border-[#262238]"><div className="space-y-1"><div className="text-xs font-bold text-white">{String(d.decision).toUpperCase()} • confiança {Number(d.confidence||0).toFixed(0)}%</div><div className={`text-[11px] font-bold ${perfTone(d.performance_action)}`}>{perfLabel(d.performance_action)} • evidência {String(d.evidence_level||'insufficient').toUpperCase()}</div><div className="text-[11px] text-gray-400">{Number(d.valid_clicks||0)} cliques • {Number(d.conversions_count||0)} conversões • {Number(d.conversion_rate||0).toFixed(2)}% CVR • R$ {Number(d.commission_earned||0).toFixed(2)} comissão</div><div className="text-[11px] text-gray-500">Canal: {d.recommended_channel||'a definir'} {d.recommended_sub_id?`• Sub ID: ${d.recommended_sub_id}`:''}</div></div>{['promote','test'].includes(String(d.decision))&&!d.product_id?<Button onClick={()=>prepare(d)} disabled={preparing===d.id} className="bg-[#7C3AED] text-white">{preparing===d.id?'Preparando...':'Preparar campanha'}</Button>:<span className="text-[10px] text-gray-500">{d.product_id?'Campanha preparada':'Aguardando mais evidência'}</span>}</div>)}</div>:<div className="p-4 rounded-xl bg-[#0B0D14] text-xs text-gray-400 text-center">Nenhuma decisão autônoma ainda. O Hunter não cria decisão sem evidência real.</div>}</div>
  <div className="p-5 rounded-2xl bg-[#101722] border border-[#00F2FF]/30"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><h2 className="text-sm font-bold text-white flex gap-2"><RadarIcon className="w-4 text-[#00F2FF]"/>Hunter Proativo</h2><p className="text-xs text-gray-400">Aprende com o desempenho e caça sozinho produtos semelhantes aos vencedores a cada 6 horas.</p></div><Button onClick={runMlNow} disabled={mlManualRunning} variant="outline" className="border-[#FFE600]/50 text-[#FFE600] bg-[#FFE600]/5"><RefreshCw className={`w-4 mr-2 ${mlManualRunning?'animate-spin':''}`}/>{mlManualRunning?'Buscando Mercado Livre...':'Buscar agora • Mercado Livre'}</Button></div><div className="mt-4">{proactive.length?<div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{proactive.map((p,i)=><DiscoveredProductCard key={p.id} product={p} rank={i+1} onApprove={approve} onDiscard={discard} onWhyPicked={()=>why(p)} onToggleWatchlist={toggle} isWatchlisted={watch.has(p.external_id||p.title)}/>)}</div>:<div className="p-5 text-center text-xs text-gray-400 bg-[#0B0D14] rounded-xl">Aguardando evidência real. Nenhuma recomendação artificial será criada.</div>}</div><div className="mt-4 border-t border-[#243040] pt-4"><div className="flex items-center justify-between mb-3"><div><h3 className="text-xs font-bold text-white uppercase">Histórico de Varreduras</h3><p className="text-[11px] text-gray-500 mt-1">As execuções ficam salvas e continuam disponíveis depois que o aviso some.</p></div><Button onClick={loadScanHistory} variant="ghost" className="h-8 text-xs text-[#00F2FF]"><RefreshCw className="w-3 mr-1"/>Atualizar</Button></div>{scanHistory.length?<div className="space-y-2 max-h-72 overflow-y-auto pr-1">{scanHistory.map((h:any)=><div key={h.id} className="p-3 rounded-xl bg-[#0B0D14] border border-[#232738]"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-2"><div className="flex items-center gap-2"><span className={`w-2 h-2 rounded-full ${h.status==='success'?'bg-emerald-400':'bg-rose-400'}`}/><span className="text-xs font-bold text-white">{h.marketplace}</span><span className="text-[10px] text-gray-500">{h.run_type==='automatic'?'AUTOMÁTICA':'MANUAL'} • {scanDate(h.created_at)}</span></div><div className="text-[11px] text-gray-300">{Number(h.trend_keywords||0)} tendências • {Number(h.categories_predicted||0)} categorias • {Number(h.highlights_checked||0)} posições • {Number(h.items_resolved||0)} anúncios • <span className="text-[#FFE600]">{Number(h.candidates||0)} oportunidades</span> • <span className="text-emerald-400">{Number(h.saved||0)} salvas</span></div></div>{h.error_message&&<div className="text-[11px] text-rose-400 mt-2">{h.error_message}</div>}</div>)}</div>:<div className="p-4 rounded-xl bg-[#0B0D14] text-xs text-gray-500 text-center">Nenhuma varredura registrada ainda.</div>}</div></div>
  <form onSubmit={find} className="p-5 rounded-2xl bg-[#141624] border border-[#7000FF]/40 flex gap-3"><input value={natural} onChange={e=>setNatural(e.target.value)} placeholder="Ex: Quero secadores com boa comissão na Shopee" className="field flex-1"/><Button disabled={parsing||searching}><Sparkles className="w-4 mr-2"/>{parsing?'Interpretando...':'Caçar com IA'}</Button></form>
  <div className="p-5 rounded-2xl bg-[#141622] border border-[#232738] space-y-4"><div className="flex items-center justify-between border-b border-[#1E2232] pb-3"><h3 className="text-xs font-bold text-white uppercase flex gap-2"><SlidersHorizontal className="w-4 text-[#00F2FF]"/>Critérios avançados</h3><span className="text-[10px] text-gray-400 font-mono">{marketplace==='TikTok Shop'?'até 20':limit} por página • {marketLabel}</span></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Field label="Palavra-chave"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ex: secador, projetor..." className="field"/></Field><Field label="Categoria"><select value={category} onChange={e=>setCategory(e.target.value)} className="field"><option>Todas</option><option>Casa e Cozinha</option><option>Eletrônicos & Áudio</option><option>Beleza & Cuidados</option><option>Moda & Acessórios</option><option>Geral</option></select></Field><Field label="Preço mínimo"><input type="number" value={minPrice} onChange={e=>setMinPrice(e.target.value?+e.target.value:'')} className="field"/></Field><Field label="Preço máximo"><input type="number" value={maxPrice} onChange={e=>setMaxPrice(e.target.value?+e.target.value:'')} className="field"/></Field><Field label="Vendas mínimas"><input type="number" value={minSales} onChange={e=>setMinSales(e.target.value?+e.target.value:'')} className="field"/></Field><Field label="Avaliação mínima"><input type="number" step="0.1" value={minRating} onChange={e=>setMinRating(e.target.value?+e.target.value:'')} className="field"/></Field><Field label="Comissão mínima (%)"><input type="number" value={estimatedCommissionRate} onChange={e=>setEstimatedCommissionRate(e.target.value?+e.target.value:'')} className="field" placeholder={marketplace==='Mercado Livre'?'Não fornecida pelo ML':'Ex: 10'}/></Field><Field label="Marketplace"><select value={marketplace} onChange={e=>{setMarketplace(e.target.value);setResults([]);setHasMore(false);if(e.target.value==='TikTok Shop'&&limit>20)setLimit(20)}} className="field"><option value="Shopee">Shopee (API Conectada)</option><option value="Mercado Livre">Mercado Livre (Conectado)</option><option value="TikTok Shop">TikTok Shop (Aguardando aprovação)</option></select></Field><Field label="Quantidade"><select value={limit} onChange={e=>setLimit(+e.target.value)} className="field"><option value={10}>10 produtos</option><option value={20}>20 produtos</option>{marketplace!=='TikTok Shop'&&<option value={30}>30 produtos</option>}</select></Field></div><div className="flex justify-end"><Button onClick={()=>search()} disabled={searching} className="bg-[#00F2FF] text-[#0A0B10] font-bold"><Search className="w-4 mr-2"/>{searching?'Consultando API...':`Executar Busca na ${marketplace}`}</Button></div></div>
  <div className="space-y-4"><h3 className="text-sm font-bold text-white">Resultados da Busca na {marketplace} ({results.length})</h3>{searching?<div className="text-center py-16 text-gray-400"><RefreshCw className="w-7 h-7 animate-spin mx-auto mb-3"/>Consultando {marketLabel}...</div>:results.length===0?<div className="p-12 text-center rounded-2xl bg-[#141622] border border-[#232738] text-gray-400">{marketplace==='TikTok Shop'?'TikTok Shop preparado. A busca ficará operacional quando a aprovação externa for liberada.':'Digite um produto, ajuste os filtros e execute a busca.'}</div>:<div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{results.map((p,i)=><DiscoveredProductCard key={p.id} product={p} rank={i+1} onApprove={approve} onDiscard={discard} onWhyPicked={()=>why(p)} onToggleWatchlist={toggle} isWatchlisted={watch.has(p.external_id||p.title)}/>)}</div>}{results.length>0&&hasMore&&<div className="flex justify-center"><Button onClick={loadMore} disabled={loadingMore} variant="outline" className="border-[#00F2FF]/40 text-[#00F2FF]"><Layers className="w-4 mr-2"/>{loadingMore?'Carregando...':'Carregar mais produtos'}</Button></div>}</div>
  <style>{`.field{width:100%;height:42px;padding:0 12px;border-radius:9px;background:#0B0D14;border:1px solid #2B3047;color:#fff;font-size:12px;outline:none}.field:focus{border-color:#00F2FF}`}</style>
 </div>
}
