import React,{useEffect,useState}from'react'
import{Compass,Search,Sparkles,SlidersHorizontal,RefreshCw,ShieldCheck,Layers,Radar as RadarIcon,BrainCircuit}from'lucide-react'
import{Button}from'@/components/ui/button'
import{DiscoveredProductCard}from'@/components/DiscoveredProductCard'
import{hunterService,watchlistService}from'@/services/hunter'
import type{DiscoveredProductRecord,HunterSearchFilters}from'@/types/product'
import{toast}from'sonner'
const ORIGIN='https://radar-de-produtos-ia-l7t2mrlbl.vercel.app';function ensure(){if(typeof window==='undefined')return true;if(window.location.hostname.endsWith('.vercel.app')&&window.location.origin!==ORIGIN){window.location.replace(ORIGIN+window.location.pathname+window.location.search);return false}return true}
function pp(x:any):DiscoveredProductRecord{return{id:`proactive_${x.id}`,external_id:String(x.external_id||''),platform:'Shopee',title:String(x.title||''),image_url:x.image_url||'',category:String(x.niche_key||'Shopee'),niche:String(x.niche_key||''),price:Number(x.price||0),promo_price:Number(x.price||0),commission_rate:Number(x.commission_rate||0),commission_amount:Number(x.commission_amount||0),sales_count:Number(x.sales_count||0),reviews_count:0,rating:Number(x.rating||0),seller:'',product_url:x.product_url||'',affiliate_url:x.affiliate_url||'',competition_level:0,trends_score:0,demand_score:Number(x.sales_count||0),opportunity_score:Number(x.proactive_score||0),opportunity_level:Number(x.proactive_score||0)>=80?'hot':'good',status:'pending',source:'shopee_affiliate_api',raw_data:{proactive:true},created:x.discovered_at||'',updated:x.last_seen_at||''}as any}
export default function HunterPage(){const[query,setQuery]=useState(''),[category,setCategory]=useState('Todas'),[marketplace,setMarketplace]=useState('Shopee'),[results,setResults]=useState<DiscoveredProductRecord[]>([]),[proactive,setProactive]=useState<DiscoveredProductRecord[]>([]),[intel,setIntel]=useState<any>(null),[searching,setSearching]=useState(false),[watch,setWatch]=useState<Set<string>>(new Set()),[natural,setNatural]=useState('');useEffect(()=>{if(!ensure())return;Promise.allSettled([watchlistService.getWatchlist().then(xs=>setWatch(new Set(xs.flatMap(x=>[x.external_id,x.title].filter(Boolean)as string[])))),hunterService.getProactiveOpportunities(12).then(xs=>setProactive(xs.map(pp))),hunterService.getIntelligence().then(setIntel)])},[])
const filters=():HunterSearchFilters=>({query,category,marketplace,limit:30,offset:0});const search=async(o?:any)=>{const q=o?.query??query;if(!q.trim()&&category==='Todas')return toast.error('Informe uma palavra-chave.');setSearching(true);try{const r=await hunterService.searchMarketplace({...filters(),...o,query:q});setResults(r.products||[])}catch(e:any){toast.error(e.message)}finally{setSearching(false)}};const find=async(e:any)=>{e.preventDefault();const p=await hunterService.findForMe(natural);setQuery(p.query||natural);await search({query:p.query||natural})};const approve=async(p:any)=>{try{if(p.source==='shopee_affiliate_api')await hunterService.importShopeeProduct(p);else if(p.platform==='Mercado Livre')await hunterService.importMercadoLivreProduct(p);setResults(x=>x.filter(y=>y.id!==p.id));setProactive(x=>x.filter(y=>y.id!==p.id));toast.success('Produto salvo no Radar.')}catch(e:any){toast.error(e.message)}};const discard=(p:any)=>{setResults(x=>x.filter(y=>y.id!==p.id));setProactive(x=>x.filter(y=>y.id!==p.id))};const toggle=async(p:any)=>{try{const k=p.external_id||p.title,r=await watchlistService.toggleWatchlist({external_id:k,platform:p.platform,title:p.title,image_url:p.image_url,product_url:p.product_url,category:p.category,price:p.price,commission_rate:p.commission_rate,commission_amount:p.commission_amount,sales_count:p.sales_count,rating:p.rating,opportunity_score:p.opportunity_score});setWatch(s=>{const n=new Set(s);r.action==='added'?n.add(k):n.delete(k);return n})}catch{}}
const t=intel?.totals||{clicks:0,conversions:0,commission:0,conversion_rate:0};return <div className="space-y-6 max-w-7xl mx-auto pb-16"><div className="pb-4 border-b border-[#1E2232]"><div className="text-[10px] text-[#00F2FF] flex gap-2"><ShieldCheck className="w-3 h-3"/>APIS OFICIAIS CONECTADAS</div><h1 className="text-3xl font-extrabold text-white flex gap-2"><Compass className="w-7"/>Caçador de Oportunidades</h1></div>
<div className="p-5 rounded-2xl bg-[#121522] border border-[#7000FF]/35"><h2 className="text-sm font-bold text-white flex gap-2 mb-4"><BrainCircuit className="w-4 text-[#00F2FF]"/>Inteligência do Hunter</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Cliques válidos',t.clicks],['Conversões',t.conversions],['Taxa de conversão',`${t.conversion_rate}%`],['Comissão',`R$ ${Number(t.commission).toFixed(2)}`]].map(([a,b])=><div className="p-3 bg-[#0B0D14] rounded-xl border border-[#232738]" key={String(a)}><div className="text-[10px] text-gray-400">{a}</div><div className="text-xl font-extrabold text-white">{b}</div></div>)}</div><div className="mt-4 text-xs text-gray-400">{intel?.niches?.length?`Nichos aprendidos: ${intel.niches.slice(0,4).map((n:any)=>`${n.niche_key} (${Number(n.confidence_score).toFixed(0)})`).join(' • ')}`:'Ainda sem conversões suficientes para formar um nicho vencedor. O painel será preenchido automaticamente com cliques e vendas reais.'}</div></div>
<div className="p-5 rounded-2xl bg-[#101722] border border-[#00F2FF]/30"><h2 className="text-sm font-bold text-white flex gap-2"><RadarIcon className="w-4 text-[#00F2FF]"/>Hunter Proativo</h2><p className="text-xs text-gray-400 mb-4">Aprende com o desempenho e caça sozinho produtos semelhantes aos vencedores.</p>{proactive.length?<div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{proactive.map((p,i)=><DiscoveredProductCard key={p.id} product={p} rank={i+1} onApprove={approve} onDiscard={discard} onWhyPicked={()=>{}} onToggleWatchlist={toggle} isWatchlisted={watch.has(p.external_id||p.title)}/>)}</div>:<div className="p-5 text-center text-xs text-gray-400 bg-[#0B0D14] rounded-xl">Aguardando evidência real. Nenhuma recomendação artificial será criada.</div>}</div>
<form onSubmit={find} className="p-5 rounded-2xl bg-[#141624] border border-[#7000FF]/40 flex gap-3"><input value={natural} onChange={e=>setNatural(e.target.value)} placeholder="Ex: Quero secadores com boa comissão" className="field flex-1"/><Button><Sparkles className="w-4 mr-2"/>Caçar com IA</Button></form><div className="p-5 rounded-2xl bg-[#141622] border border-[#232738]"><div className="grid md:grid-cols-3 gap-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Produto" className="field"/><select value={category} onChange={e=>setCategory(e.target.value)} className="field"><option>Todas</option><option>Beleza & Cuidados</option><option>Casa e Cozinha</option><option>Eletrônicos & Áudio</option></select><select value={marketplace} onChange={e=>setMarketplace(e.target.value)} className="field"><option>Shopee</option><option>Mercado Livre</option><option>TikTok Shop</option></select></div><div className="flex justify-end mt-3"><Button onClick={()=>search()} disabled={searching}><Search className="w-4 mr-2"/>{searching?'Buscando...':'Executar Busca'}</Button></div></div><div>{searching?<RefreshCw className="animate-spin mx-auto"/>:<div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{results.map((p,i)=><DiscoveredProductCard key={p.id} product={p} rank={i+1} onApprove={approve} onDiscard={discard} onWhyPicked={()=>{}} onToggleWatchlist={toggle} isWatchlisted={watch.has(p.external_id||p.title)}/>)}</div>}</div><style>{`.field{height:42px;padding:0 12px;border-radius:9px;background:#0B0D14;border:1px solid #2B3047;color:#fff;font-size:12px}`}</style></div>}
