import React,{useState}from'react'
import{ExternalLink,Sparkles,Bookmark,BookmarkCheck,CheckCircle2,XCircle,AlertCircle,FlaskConical,Info,ShieldCheck,Calculator,Cpu,TrendingUp,Trophy,Coins}from'lucide-react'
import{useNavigate}from'react-router-dom'
import{ScoreRing}from'./ScoreRing'
import{OpportunityBadge}from'./OpportunityBadge'
import{MercadoLivreAffiliateAssistant}from'./MercadoLivreAffiliateAssistant'
import{Button}from'@/components/ui/button'
import type{DiscoveredProductRecord}from'@/types/product'
import{cn}from'@/lib/utils'

interface DiscoveredProductCardProps{product:DiscoveredProductRecord;onApprove:(product:DiscoveredProductRecord)=>void;onDiscard:(product:DiscoveredProductRecord)=>void;onWhyPicked:(product:DiscoveredProductRecord)=>void;onToggleWatchlist:(product:DiscoveredProductRecord)=>void;onAffiliateConfirm?:(product:DiscoveredProductRecord)=>void;isWatchlisted?:boolean;isApproving?:boolean;isDiscarding?:boolean;rank?:number}

export const DiscoveredProductCard:React.FC<DiscoveredProductCardProps>=({product,onApprove,onDiscard,onWhyPicked,onToggleWatchlist,onAffiliateConfirm,isWatchlisted=false,isApproving=false,isDiscarding=false,rank})=>{
 const navigate=useNavigate(),[affiliateOpen,setAffiliateOpen]=useState(false)
 const price=product.promo_price&&product.promo_price>0?product.promo_price:product.price,hasPromo=Boolean(product.promo_price&&product.promo_price<product.price&&product.promo_price>0)
 const isHot=product.opportunity_level==='hot',isGood=product.opportunity_level==='good',raw:any=product.raw_data||{},reason:any=raw.reason||{}
 const offersTotal=Number(raw.offers_total||reason.offers_total||0),hasRealPrice=Number(price)>0,hasRealSales=Number(product.sales_count||0)>0,hasRealRating=Number(product.rating||0)>0
 const isShopee=product.platform==='Shopee'||product.source==='shopee_affiliate_api',isML=product.platform==='Mercado Livre',sourceShort=isShopee?'Shopee':'ML',marketplaceName=isShopee?'Shopee':'Mercado Livre',marketplaceLinkLabel=isShopee?'Ver na Shopee':'Ver no Mercado Livre'
 const trendLabel=String(reason.trend_class_label||''),trendKeyword=String(reason.trend_keyword||''),trendPeriod=String(reason.trend_period||''),trendPosition=Number(reason.trend_position||0),highlightPosition=Number(reason.highlight_position||0),hasOfficialEvidence=isML&&Boolean(reason.rank_evidence&&trendKeyword)
 const hasCommission=Number(product.commission_rate||0)>0,hasAffiliateLink=Boolean(product.affiliate_url),estimatedEarning=hasRealPrice&&hasCommission?Number(price)*Number(product.commission_rate)/100:0
 const affiliateEligibility=String(reason.affiliate_eligibility||''),affiliateVerified=['eligible','eligible_by_public_rules'].includes(affiliateEligibility)||Boolean(reason.affiliate_eligible===true),affiliateRejected=['ineligible','ineligible_by_public_rules'].includes(affiliateEligibility)||Boolean(reason.affiliate_eligible===false)
 const affiliateLabel=affiliateEligibility==='eligible_by_public_rules'?'Elegível pelos critérios oficiais':affiliateEligibility==='ineligible_by_public_rules'?'Não atende aos critérios oficiais':affiliateVerified?'Elegível confirmada':affiliateRejected?'Não elegível':'Ainda não verificada'
 const affiliateBestSeller=Boolean(reason.affiliate_best_seller||reason.affiliate_best_seller_position),affiliateBestSellerPosition=Number(reason.affiliate_best_seller_position||0),extraGain=Boolean(reason.affiliate_extra_gain||reason.extra_gain),doubleConfirmed=affiliateBestSeller&&hasOfficialEvidence
 const affiliatePriority=doubleConfirmed?'double':extraGain?'extra':affiliateBestSeller?'affiliate':hasOfficialEvidence?'general':'unknown'
 const priorityLabel=affiliatePriority==='double'?'🏆 Dupla confirmação':affiliatePriority==='extra'?'💰 Ganho Extra':affiliatePriority==='affiliate'?'🔥 Prioridade Afiliado':affiliatePriority==='general'?'⚠️ Só tendência geral':'⏳ Aguardando evidência de afiliado'
 const canCommercialAction=hasRealPrice&&Boolean(product.product_url)&&(!isML||(affiliateVerified&&hasCommission&&hasAffiliateLink)),potentialLabel=product.opportunity_score>=80?'Alto Potencial':product.opportunity_score>=60?'Médio-Alto Potencial':product.opportunity_score>=40?'Potencial de Teste':'Baixo Potencial',startAffiliate=()=>{if(onAffiliateConfirm)onAffiliateConfirm(product);else setAffiliateOpen(true)}
 return <><div className={cn('group relative flex flex-col justify-between rounded-2xl bg-[#141622] border transition-all duration-300 hover:-translate-y-1 overflow-hidden',isHot?'border-[#FF3D00]/50':isGood?'border-[#00E676]/35':'border-[#232738]')}>
  <div className="relative w-full aspect-[4/3] bg-[#0A0B10] overflow-hidden"><img src={product.image_url||'https://img.usecurling.com/p/400/300?q=product'} alt={product.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" loading="lazy"/><div className="absolute inset-0 bg-gradient-to-t from-[#141622] via-transparent to-black/70"/>{rank!==undefined&&<div className="absolute top-3 left-3 px-2.5 py-1 rounded-full bg-gradient-to-r from-[#FF3D00] to-[#FF8500] text-[#0A0B10] font-mono font-black text-xs">#{rank}</div>}<div className={cn('absolute top-3 flex items-center gap-1.5 flex-wrap max-w-[75%]',rank!==undefined?'left-14':'left-3')}><OpportunityBadge level={product.opportunity_level} size="sm"/><span className="text-[10px] font-mono font-semibold px-2 py-0.5 rounded-full bg-black/80 text-[#FFE600] border border-[#FFE600]/30">{product.platform||'Mercado Livre'}</span></div><div className="absolute top-2.5 right-2.5 bg-[#0A0B10]/85 p-1 rounded-full border border-white/10"><ScoreRing score={product.opportunity_score} size="sm"/></div></div>
  <div className="p-4 flex-1 flex flex-col justify-between space-y-3"><div><h3 className="text-sm font-bold text-white leading-snug line-clamp-2 mb-1.5">{product.title}</h3><div className="text-[11px] text-gray-400 font-mono">Fonte: <strong className="text-gray-300">{marketplaceName}</strong></div></div>
  {isML&&<div className={cn('p-3 rounded-xl border space-y-1.5',affiliatePriority==='double'?'bg-[#102016] border-[#00E676]/50':affiliatePriority==='affiliate'||affiliatePriority==='extra'?'bg-[#1b1707] border-[#FFD600]/45':affiliatePriority==='general'?'bg-[#20130d] border-orange-500/40':'bg-[#11131d] border-[#2a3042]')}><div className="text-xs font-black">{priorityLabel}</div>{affiliatePriority==='general'&&<div className="text-[10px] text-orange-300">Está forte no Mercado Livre geral, mas ainda não há confirmação de destaque no ambiente de Afiliados. Não tratar como prioridade automática de divulgação.</div>}{affiliateBestSeller&&<div className="text-[10px] text-[#00E676]">Mais vendido no ambiente de Afiliados{affiliateBestSellerPosition?` • posição ${affiliateBestSellerPosition}`:''}</div>}{extraGain&&<div className="text-[10px] text-[#FFD600] flex gap-1"><Coins className="w-3 h-3"/>Oferta/Ganho Extra confirmado</div>}{doubleConfirmed&&<div className="text-[10px] text-[#00E676]">Confirmado em Afiliados + ranking/tendência geral.</div>}</div>}
  {hasOfficialEvidence&&<div className="p-3 rounded-xl bg-[#10180f] border border-[#00E676]/35 space-y-1"><div className="text-[10px] uppercase font-black text-[#00E676] flex gap-1"><ShieldCheck className="w-3 h-3"/>Evidência Mercado Livre geral</div><div className="text-[11px] text-white"><TrendingUp className="w-3 h-3 inline mr-1"/><b>{trendKeyword}</b> • {trendLabel||'Tendência oficial'}</div><div className="text-[11px] text-gray-300"><Trophy className="w-3 h-3 inline mr-1"/>{highlightPosition?`Produto #${highlightPosition} entre os mais vendidos da categoria`:'Presente no ranking oficial de mais vendidos'}</div><div className="text-[10px] text-gray-500">Isto prova demanda geral; sozinho não prova prioridade para afiliados.</div></div>}
  {isML&&<div className="p-3 rounded-xl bg-[#11131d] border border-[#FFD600]/25 space-y-1.5 text-[10px] font-mono"><div className="uppercase font-black text-[#FFD600]">Afiliados Mercado Livre</div><div className="flex justify-between"><span className="text-gray-400">Elegibilidade:</span><span className={affiliateVerified?'text-[#00E676]':affiliateRejected?'text-red-400':'text-amber-300'}>{affiliateLabel}</span></div><div className="flex justify-between"><span className="text-gray-400">Comissão:</span><span className={hasCommission?'text-[#FFD600]':'text-amber-300'}>{hasCommission?`${Number(product.commission_rate).toFixed(2)}%`:'Consultar no Portal'}</span></div><div className="flex justify-between"><span className="text-gray-400">Link:</span><span className={hasAffiliateLink?'text-[#00E676]':'text-amber-300'}>{hasAffiliateLink?'Confirmado':'Ainda não informado'}</span></div><div className="flex justify-between"><span className="text-gray-400">Você ganha:</span><span className={estimatedEarning>0?'text-[#00E676] font-bold':'text-gray-400'}>{estimatedEarning>0?`R$ ${estimatedEarning.toFixed(2)} por venda`:'Aguardando comissão'}</span></div>{(!hasCommission||!hasAffiliateLink)&&<Button size="sm" variant="outline" onClick={startAffiliate} className="w-full h-7 mt-1 border-[#FFD600]/40 text-[#FFD600]">Assistente de comissão + link</Button>}</div>}
  <div className="space-y-1 py-2 px-2.5 rounded-xl bg-[#0D0F18] border border-[#202538] text-[10px] font-mono"><div className="text-[9px] uppercase text-gray-500 font-bold"><Info className="w-3 h-3 inline mr-1"/>Transparência</div><div className="flex justify-between"><span>Preço:</span><span className="text-[#00E676]">{hasRealPrice?'Dado Real':'Não informado'}</span></div><div className="flex justify-between"><span>Vendas:</span><span>{hasRealSales?product.sales_count:hasOfficialEvidence?'Ranking confirmado; quantidade não informada':'Não informado'}</span></div><div className="flex justify-between"><span>Score:</span><span className="text-[#00F2FF]"><Calculator className="w-2.5 h-2.5 inline"/> {product.opportunity_score}/100</span></div><div className="flex justify-between"><span>Potencial:</span><span className="text-[#C084FC]"><Cpu className="w-2.5 h-2.5 inline"/> {potentialLabel}</span></div></div>
  <div className="space-y-2 pt-1 border-t border-[#232738]"><div className="grid grid-cols-2 gap-2 bg-[#10121A] p-2.5 rounded-xl"><div><span className="text-[10px] text-gray-400 block">Preço</span><b>{hasRealPrice?`R$ ${Number(price).toFixed(2)}`:'Não informado'}</b>{hasPromo&&<span className="text-[10px] text-gray-500 line-through block">R$ {product.price.toFixed(2)}</span>}</div><div><span className="text-[10px] text-gray-400 block">Prioridade</span><div className="text-[10px] mt-1">{priorityLabel}</div></div></div>{product.product_url&&<a href={product.product_url} target="_blank" rel="noreferrer" className="w-full h-8 inline-flex items-center justify-center rounded-md border border-[#00F2FF]/35 text-[#00F2FF] text-xs gap-1"><ExternalLink className="w-3 h-3"/>{marketplaceLinkLabel}</a>}<Button variant="outline" size="sm" onClick={()=>onWhyPicked(product)} className="w-full h-8 text-xs border-[#7000FF]/40 text-[#C084FC]"><Sparkles className="w-3.5 h-3.5 mr-1"/>Por que a IA escolheu este produto?</Button><div className="grid grid-cols-2 gap-1.5"><Button variant="outline" size="sm" disabled={isDiscarding||isApproving} onClick={()=>onDiscard(product)}><XCircle className="w-3.5 h-3.5 mr-1"/>Descartar</Button><Button variant="outline" size="sm" onClick={()=>onToggleWatchlist(product)}>{isWatchlisted?<BookmarkCheck className="w-3.5 h-3.5 mr-1"/>:<Bookmark className="w-3.5 h-3.5 mr-1"/>}{isWatchlisted?'Salvo':'Monitorar'}</Button>{canCommercialAction&&<><Button size="sm" onClick={()=>navigate(`/laboratorio?discoveredId=${product.id}`)}><FlaskConical className="w-3.5 h-3.5 mr-1"/>Campanha</Button><Button size="sm" onClick={()=>onApprove(product)}><CheckCircle2 className="w-3.5 h-3.5 mr-1"/>Aprovar</Button></>}</div></div></div>
 </div>{isML&&<MercadoLivreAffiliateAssistant product={product} open={affiliateOpen} onOpenChange={setAffiliateOpen}/>}</>}
