import React,{useEffect,useMemo,useState}from'react'
import{ExternalLink,ClipboardPaste,Copy,CheckCircle2,Calculator,ShieldCheck,Search,Link2,Zap,Send}from'lucide-react'
import{toast}from'sonner'
import pb from '@/lib/pocketbase/client'
import type{DiscoveredProductRecord}from'@/types/product'
import{Button}from'@/components/ui/button'
import{Input}from'@/components/ui/input'
import{Label}from'@/components/ui/label'
import{Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle}from'@/components/ui/dialog'

const AFFILIATE_HOME='https://www.mercadolivre.com.br/l/comece-a-recomendar'
type Props={product:DiscoveredProductRecord;open:boolean;onOpenChange:(open:boolean)=>void}
function parseRate(text:string){const m=String(text||'').replace(',','.').match(/(\d{1,2}(?:\.\d{1,2})?)\s*%/);if(!m)return null;const n=Number(m[1]);return Number.isFinite(n)&&n>0&&n<=100?n:null}
function extractMlUrl(text:string){const matches=String(text||'').match(/https:\/\/[^\s]+/g)||[];return matches.find(value=>{try{const h=new URL(value).hostname.toLowerCase();return h==='meli.la'||h.endsWith('.meli.la')||h==='mercadolivre.com.br'||h.endsWith('.mercadolivre.com.br')||h==='mercadolivre.com'||h.endsWith('.mercadolivre.com')||h==='mercadolibre.com'||h.endsWith('.mercadolibre.com')}catch{return false}})||''}
export function MercadoLivreAffiliateAssistant({product,open,onOpenChange}:Props){
 const raw:any=product.raw_data||{},proactiveId=String(raw.proactive_id||'')
 const[rate,setRate]=useState(product.commission_rate>0?String(product.commission_rate).replace('.',','):'');const[link,setLink]=useState(product.affiliate_url||'');const[saving,setSaving]=useState(false)
 const price=Number(product.promo_price&&product.promo_price>0?product.promo_price:product.price||0),rateNumber=Number(String(rate).replace(',','.')),earning=useMemo(()=>price>0&&Number.isFinite(rateNumber)&&rateNumber>0?price*rateNumber/100:0,[price,rateNumber])
 const ready=Boolean(extractMlUrl(link));
 const adText=useMemo(()=>{const p=price>0?`\n💰 R$ ${price.toFixed(2).replace('.',',')}`:'';return `🔥 OFERTA ENCONTRADA NO MERCADO LIVRE\n\n${product.title}${p}\n\n🛒 Confira aqui: ${link||'[cole seu link de afiliado]'}\n\n⚡ Preço e disponibilidade podem mudar no Mercado Livre.`},[product.title,price,link])
 useEffect(()=>{if(open){setRate(product.commission_rate>0?String(product.commission_rate).replace('.',','):'');setLink(product.affiliate_url||'')}},[open,product.commission_rate,product.affiliate_url])
 const openProduct=async()=>{const confirmedUrl=String(product.product_url||'').trim(),fallback=`https://lista.mercadolivre.com.br/${encodeURIComponent(String(product.title||'').trim())}`;try{await navigator.clipboard.writeText(confirmedUrl||String(product.title||''))}catch{}window.open(confirmedUrl||fallback,'_blank','noopener,noreferrer');toast.success('No Mercado Livre, clique em Compartilhar na Barra de Afiliados e copie o link.')}
 const captureClipboard=async()=>{try{const text=await navigator.clipboard.readText();if(!text)return toast.error('Nada copiado ainda.');const u=extractMlUrl(text),r=parseRate(text);if(u)setLink(u);if(r)setRate(String(r).replace('.',','));if(u)return toast.success(r?'Link e comissão capturados. Já pode salvar e divulgar.':'Link capturado. Já pode copiar o anúncio; informe a comissão quando disponível.');toast.error('Não encontrei um link oficial do Mercado Livre no conteúdo copiado.')}catch{toast.error('O navegador não permitiu ler a área de transferência. Cole o link no campo abaixo.')}}
 const copyAd=async()=>{if(!ready)return toast.error('Primeiro cole ou capture seu link de afiliado.');try{await navigator.clipboard.writeText(adText);toast.success('Anúncio copiado. Pronto para divulgar no WhatsApp ou Telegram.')}catch{toast.error('Não consegui copiar automaticamente.')}}
 const save=async()=>{const rv=Number(String(rate).replace(',','.'));if(!proactiveId)return toast.error('Esta oportunidade ainda não possui ID do Hunter.');if(!Number.isFinite(rv)||rv<=0||rv>100)return toast.error('Informe a comissão exata exibida pelo Mercado Livre.');if(!ready)return toast.error('Cole o link oficial gerado pelo Mercado Livre.');setSaving(true);try{const res=await fetch('/api/hunter/proactive',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${pb.authStore.token}`},body:JSON.stringify({id:proactiveId,operation:'affiliate_confirm',commission_rate:rv,affiliate_url:link.trim()})}),data=await res.json().catch(()=>({}));if(!res.ok||!data?.success)throw new Error(data?.error||'Falha ao salvar.');toast.success(`Produto pronto. Ganho estimado: R$ ${Number(data?.item?.commission_amount||earning).toFixed(2)} por venda.`);onOpenChange(false);window.setTimeout(()=>window.location.reload(),450)}catch(e:any){toast.error(e?.message||'Falha ao salvar dados de afiliado.')}finally{setSaving(false)}}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="bg-[#10121A] border-[#FFD600]/30 text-white sm:max-w-2xl"><DialogHeader><DialogTitle className="text-[#FFD600] flex items-center gap-2"><Zap className="w-5 h-5"/>VENDA RÁPIDA • Mercado Livre</DialogTitle><DialogDescription className="text-gray-400">Só 3 passos: gerar o link, colar aqui e copiar o anúncio.</DialogDescription></DialogHeader><div className="space-y-3">
 <div className="grid grid-cols-3 gap-2 text-center text-[11px]"><div className="rounded-lg border border-[#FFE600]/30 p-2"><b className="text-[#FFE600]">1</b><br/>Gerar link</div><div className="rounded-lg border border-[#00F2FF]/30 p-2"><b className="text-[#00F2FF]">2</b><br/>Colar link</div><div className="rounded-lg border border-[#00E676]/30 p-2"><b className="text-[#00E676]">3</b><br/>Divulgar</div></div>
 <div className="rounded-xl border border-[#00E676]/25 bg-[#07140d] p-3"><div className="text-xs font-bold text-[#00E676] flex items-center gap-1"><ShieldCheck className="w-4 h-4"/>Produto selecionado pelo Radar</div><div className="text-sm font-bold mt-1">{product.title}</div>{price>0&&<div className="text-lg font-black text-[#FFE600] mt-1">R$ {price.toFixed(2).replace('.',',')}</div>}</div>
 <Button onClick={openProduct} className="w-full h-11 bg-[#FFE600] text-black hover:bg-[#FFE600]/90 font-black"><ExternalLink className="w-4 h-4 mr-2"/>1 • GERAR LINK AGORA</Button>
 <div className="rounded-xl border border-[#2A2F42] bg-[#0B0D14] p-3 space-y-2"><div className="text-xs font-semibold flex items-center gap-1"><Link2 className="w-4 h-4 text-[#00F2FF]"/>Voltou do Mercado Livre?</div><Button type="button" variant="outline" onClick={captureClipboard} className="w-full border-[#00F2FF]/35 text-[#00F2FF]"><ClipboardPaste className="w-4 h-4 mr-2"/>2 • COLAR/CAPTURAR LINK COPIADO</Button><Input value={link} onChange={e=>setLink(e.target.value)} placeholder="https://meli.la/..." className="bg-[#111521] border-[#30364B]"/></div>
 <Button onClick={copyAd} disabled={!ready} className="w-full h-11 bg-[#00E676] text-black hover:bg-[#00E676]/90 font-black"><Send className="w-4 h-4 mr-2"/>3 • COPIAR ANÚNCIO PRONTO</Button>
 {ready&&<div className="rounded-xl border border-[#00E676]/25 bg-[#07140d] p-3"><div className="text-[10px] uppercase text-[#00E676] font-black mb-2">Prévia para WhatsApp / Telegram</div><pre className="whitespace-pre-wrap text-xs text-gray-200 font-sans">{adText}</pre></div>}
 <div className="rounded-xl border border-[#2A2F42] p-3"><div className="text-[10px] text-gray-400 mb-2">OPCIONAL • salvar comissão para o Radar calcular seu ganho</div><div className="grid grid-cols-[140px_1fr] gap-3 items-end"><div><Label className="text-xs">Comissão (%)</Label><Input value={rate} onChange={e=>setRate(e.target.value)} placeholder="Ex.: 12" className="bg-[#111521] border-[#30364B]"/></div><div className="text-right"><div className="text-[10px] text-gray-400">Ganho estimado</div><div className="text-xl font-black text-[#00E676] flex justify-end items-center gap-1"><Calculator className="w-4 h-4"/>{earning>0?`R$ ${earning.toFixed(2)}`:'—'}</div></div></div></div>
 </div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Fechar</Button><Button onClick={save} disabled={saving||!rate||!ready} className="bg-[#00F2FF] text-black"><CheckCircle2 className="w-4 h-4 mr-2"/>{saving?'Salvando...':'Salvar link + comissão'}</Button></DialogFooter></DialogContent></Dialog>
}
