import { getMercadoLivreSession, requireSupabaseUser } from '../../server/mercadolivre.js'

const PRIORITY_CATEGORIES=['Eletrônicos, Áudio e Vídeo','Celulares e Telefones','Informática','Beleza e Cuidado Pessoal','Esportes e Fitness','Acessórios para Veículos','Eletrodomésticos','Games','Calçados, Roupas e Bolsas','Casa, Móveis e Decoração']
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
function clamp(n:number,min:number,max:number){return Math.max(min,Math.min(max,n))}
async function mlJson(url:string,token:string){const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`,Accept:'application/json','User-Agent':'RadarIA/1.0'}});const d=await r.json().catch(()=>({}));if(!r.ok){const e:any=new Error(d?.message||d?.error||`Mercado Livre HTTP ${r.status}`);e.status=r.status;throw e}return d}
async function resolveProduct(entry:any,token:string){const id=String(entry?.id||''),type=String(entry?.type||'').toUpperCase();if(!id)return null
 let p:any=null
 if(type==='PRODUCT'){p=await mlJson(`https://api.mercadolibre.com/products/${encodeURIComponent(id)}`,token)}
 else if(type==='USER_PRODUCT'||id.startsWith('MLBU')){try{const up=await mlJson(`https://api.mercadolibre.com/user-products/${encodeURIComponent(id)}`,token);const cid=String(up?.catalog_product_id||up?.product_id||'');if(cid)p=await mlJson(`https://api.mercadolibre.com/products/${encodeURIComponent(cid)}`,token)}catch{return null}}
 else if(type==='ITEM'){try{const item=await mlJson(`https://api.mercadolibre.com/items/${encodeURIComponent(id)}`,token);return{external_id:String(item.id),title:String(item.title||''),image_url:String(item?.pictures?.[0]?.secure_url||item?.thumbnail||'').replace(/^http:/,'https:'),product_url:String(item.permalink||''),price:Number(item.price||0),seller_id:String(item.seller_id||''),item_condition:String(item.condition||''),sold_quantity:Number(item.sold_quantity||0),free_shipping:Boolean(item?.shipping?.free_shipping),offer_item_id:String(item.id),catalog_product_id:String(item.catalog_product_id||''),category_id:String(item.category_id||''),price_source:'item_detail'}}catch{return null}}
 if(!p?.id||!p?.name)return null
 const winner=p?.buy_box_winner||{};let price=Number(winner?.price||0),sellerId=String(winner?.seller_id||''),condition=String(winner?.condition||''),offerItemId=String(winner?.item_id||''),freeShipping=Boolean(winner?.shipping?.free_shipping),priceSource=price>0?'buy_box_winner':''
 if(price<=0||!sellerId||!condition){try{const c=await mlJson(`https://api.mercadolibre.com/products/${encodeURIComponent(String(p.id))}/items`,token);const offers=(Array.isArray(c?.results)?c.results:[]).filter((x:any)=>Number(x?.price||0)>0).sort((a:any,b:any)=>Number(a.price)-Number(b.price));if(offers[0]){const o=offers[0];if(price<=0){price=Number(o.price||0);priceSource='catalog_competition_lowest_offer'}sellerId=sellerId||String(o.seller_id||'');condition=condition||String(o.condition||'');offerItemId=offerItemId||String(o.item_id||'');freeShipping=freeShipping||Boolean(o?.shipping?.free_shipping||o?.shipping_cost===0)}}catch{}}
 return{external_id:String(p.id),title:String(p.name||''),image_url:String(p?.pictures?.[0]?.secure_url||p?.pictures?.[0]?.url||p?.thumbnail||'').replace(/^http:/,'https:'),product_url:String(p?.permalink||p?.url||''),price,seller_id:sellerId,item_condition:condition,sold_quantity:Number(winner?.sold_quantity||p?.sold_quantity||0),free_shipping:freeShipping,offer_item_id:offerItemId,catalog_product_id:String(p.id),category_id:String(winner?.category_id||p?.category_id||''),price_source:priceSource}}
async function enrichEligibility(rows:any[],token:string){const cache=new Map<string,string>();for(const row of rows){const reason=row.reason||{},sid=String(reason.seller_id||''),condition=String(reason.item_condition||'').toLowerCase();reason.affiliate_commission_status='not_available_in_public_developer_api';reason.affiliate_eligibility_source='mercadolivre_public_program_rules';if(!sid||!condition){reason.affiliate_eligibility='unknown';continue}let level=cache.get(sid)||'';if(!level){try{const u=await mlJson(`https://api.mercadolibre.com/users/${encodeURIComponent(sid)}?attributes=seller_reputation`,token);level=String(u?.seller_reputation?.level_id||'');cache.set(sid,level)}catch{reason.affiliate_eligibility='unknown';continue}}const green=level==='4_light_green'||level==='5_green',isNew=condition==='new';reason.seller_reputation_level=level;reason.affiliate_eligibility=green&&isNew?'eligible_by_public_rules':'ineligible_by_public_rules';reason.affiliate_eligible=green&&isNew}}

export default async function handler(req:any,res:any){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});try{const ctx=await requireSupabaseUser(req),{session,setCookie}=await getMercadoLivreSession(req);if(setCookie)res.setHeader('Set-Cookie',setCookie);const cats=await mlJson('https://api.mercadolibre.com/sites/MLB/categories',session.access_token);const chosen=(Array.isArray(cats)?cats:[]).filter((c:any)=>PRIORITY_CATEGORIES.some(n=>norm(String(c.name||''))===norm(n))).slice(0,10);const rows:any[]=[],seen=new Set<string>(),diagnostics:any[]=[]
 for(const cat of chosen){try{const h=await mlJson(`https://api.mercadolibre.com/highlights/MLB/category/${encodeURIComponent(String(cat.id))}`,session.access_token);const content=Array.isArray(h?.content)?h.content:[];let resolved=0;for(const entry of content.slice(0,8)){try{const item=await resolveProduct(entry,session.access_token);if(!item?.external_id||!item?.title||seen.has(item.external_id))continue;seen.add(item.external_id);resolved++;const pos=Number(entry?.position||20),price=Number(item.price||0);let score=90-Math.min(18,(pos-1)*2);if(price>=20&&price<=300)score+=4;else if(price<=800)score+=2;if(item.free_shipping)score+=2;score=clamp(score,60,98);rows.push({user_id:ctx.user.id,platform:'Mercado Livre',niche_key:norm(String(cat.name||'mercadolivre_mais_vendidos')).replace(/\s+/g,'_'),search_query:`Mais vendidos • ${String(cat.name||'')}`,external_id:item.external_id,title:item.title,image_url:item.image_url,product_url:item.product_url||'',affiliate_url:null,price,commission_rate:0,commission_amount:0,sales_count:Number(item.sold_quantity||0),rating:0,base_score:score,niche_confidence:0,proactive_score:score,reason:{source:'mercadolivre_affiliate_priority_best_sellers_v1',evidence_source:'Mercado Livre API oficial /highlights',affiliate_program_recommended:true,affiliate_recommended_source:'mercadolivre_affiliates_content_mais_vendidos',affiliate_best_seller:true,affiliate_best_seller_position:pos,affiliate_best_seller_category:String(cat.name||''),affiliate_best_seller_note:'Página Mais vendidos é recomendada pelo próprio conteúdo oficial de Afiliados como fonte para divulgação.',highlight_position:pos,highlight_type:String(entry?.type||''),highlight_scope:'categoria',category_id:String(cat.id),catalog_product_id:item.catalog_product_id||null,offer_item_id:item.offer_item_id||null,seller_id:item.seller_id||null,item_condition:item.item_condition||null,price_source:item.price_source||null,price_available:price>0,link_available:Boolean(item.product_url),rank_evidence:true,free_shipping:Boolean(item.free_shipping),conversion_learning_enabled:false,affiliate_link_required_after_selection:true,autonomous_prepare_enabled:false},last_seen_at:new Date().toISOString(),updated_at:new Date().toISOString()})}catch{}}diagnostics.push({category:String(cat.name||''),category_id:String(cat.id),highlights:content.length,resolved,status:200})}catch(e:any){diagnostics.push({category:String(cat.name||''),category_id:String(cat.id),status:Number(e?.status||0)||null,error:String(e?.message||e)})}}
 rows.sort((a,b)=>Number(b.proactive_score)-Number(a.proactive_score));const selected=rows.slice(0,40);await enrichEligibility(selected,session.access_token);if(selected.length){const wr=await fetch(`${ctx.url}/rest/v1/hunter_proactive_opportunities?on_conflict=user_id,platform,external_id`,{method:'POST',headers:{apikey:ctx.key,Authorization:ctx.auth,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(selected)});if(!wr.ok){const e=await wr.json().catch(()=>({}));throw new Error(e?.message||'Não foi possível salvar os Mais Vendidos prioritários.')}}return res.status(200).json({success:true,categories:chosen.length,candidates:selected.length,saved:selected.length,diagnostics,source:'mercadolivre_affiliate_priority_best_sellers_v1'})}catch(e:any){return res.status(500).json({success:false,error:String(e?.message||e||'Falha ao buscar Mais Vendidos prioritários.'),status:Number(e?.status||0)||null})}}
